about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

handler404 = 'posts.views.page_not_found'
handler500 = 'posts.views.server_error'

templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a class="btn btn-sm text-muted" href="{% url 'about:author' %}">About author</a>
    <a class="btn btn-sm text-muted" href="{% url 'about:tech' %}">About technologies</a>
  </p>
  <p class="m-0 text-dark text-center ">Social blog <span style="color:red">Ya</span>tube © {% now 'Y' %}</p>
</footer>

templates/includes/menu.html
{% if user.is_authenticated %}
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
                All authors
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'follow_index' %}">
                Favourite authors
            </a>
        </li>
    </ul>
</div>
{% endif %}

templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="margin-left:20px navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span>tube</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if request.user.is_authenticated %}
    User: {{ request.user.username }}
    <a class="btn btn-sm text-muted" href="{% url 'new_post' %}">New post</a>
    <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Change the password</a>
    <a class="btn btn-sm text-muted" href="{% url 'logout' %}">Log out</a>
    {% else %}
    <a class="btn btn-sm text-muted" href="{% url 'login' %}">Log in</a> |
    <a class="btn btn-sm text-muted" href="{% url 'signup' %}">Sign up</a>
    {% endif %}
  </nav>
</nav>

templates/includes/paginator.html
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Previous</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(current)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Next &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Next &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}